version: 3.0.0
services:
  mssql-server:
    image: mcr.microsoft.com/mssql/server
    container_name: mssql-server
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Passw0rd
    volumes:
      - data:/var/opt/mssql

volumes:
  data:
